name: csv
version: 7.1.0
description: |-
  A codec to transform between a string and a list of values.

  The string must be comma (configurable) separated values.
homepage: https://github.com/close2/csv
documentation: https://github.com/close2/csv

environment:
  sdk: ^3.10.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
