name: csv
version: 5.0.1
description: |-
  A codec to transform between a string and a list of values.

  The string must be comma (configurable) separated values.
homepage: https://github.com/close2/csv
documentation: https://github.com/close2/csv

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
