name: csv
version: 3.2.0
author: Christian Loitsch <christian@loitsch.com>
description: |-
  A codec to transform between a string and a list of values.

  The string must be comma (configurable) separated values.
homepage: https://github.com/close2/csv
documentation: https://github.com/close2/csv

environment:
  sdk: '>=2.0.0-dev.0.0 <2.1.0'

dev_dependencies:
  test: '>=0.12.8 <0.13.0'
